### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium'

### ISSUE THREAD

**Issue by Yukarlna** [jimodeniuren/RenpyEasyTranslator#1]
大佬，运行main.py 提示 ModuleNotFoundError: No module named 'selenium'.

Traceback (most recent call last):
  File "C:\Users\mufeng\Desktop\RenpyEasyTranslator-main\main.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by jimodeniuren** [comment]
你没安装selenium库，运行一下pip install selenium就可以安装了，安装好这个库之后还要安装和你的chrome浏览器版本匹配的chrome driver

**Comment by Yukarlna** [comment]
Traceback (most recent call last):
  File "C:\Users\mufeng\Desktop\RenpyEasyTranslator-main\main.py", line 139, in <module>
    with open('index.js', 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'index.js'

安装完运行提示这个

**Comment by jimodeniuren** [comment]
这个代码仓库里面有这个index.js文件，你要也下载下来和main.py放在同一个文件夹下面

**Comment by Yukarlna** [comment]
放了，但还是提示这个
![d3f32166-7051-4df9-bd7e-c516cd993776](https://github.com/user-attachments/assets/4b65c18d-f362-4bbf-9d57-aa1b20f84072)

**Comment by jimodeniuren** [comment]
应该是你的环境变量里面的PYTHONPATH之类的没有设置吧，你试试直接把main.py里面读取index.js文件的地方改成index.js文件的绝对路径看看

**Comment by Yukarlna** [comment]
可以了，多谢大佬🙏
